---
title: "Google Stroe 應用程式下載類別分析"
author: "同意啦哪次不同意_Team1"
#date: "Date：2020/12/10"
output: 
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
---

# 同意啦哪次不同意_Team1

## (KDD1) 原生資料展示
```{r, echo=FALSE, warning=FALSE}
#install.packages(c("pander","kableExtra","prettydoc")
#https://www.rdocumentation.org/packages/kableExtra/versions/1.3.1/topics/kable_styling 語法參考資料
library(data.table)
library(pander);   library(knitr);      library(kableExtra)
library(readxl)

X =as.data.frame(read_excel('/Users/juck30808/Documents/Github/USC_R_Git/2.R-tech/data/googleplaystore4_(7000).xlsX'))
#dim(X);   
#head(X,2)  

#@
pander(paste0(">> (1) APP數據Row共 ",dim(X)[1],"筆紀錄\n\n")); 
pander(paste0(">> (2) APP數據Col共 ",dim(X)[2],"筆紀錄\n\n")); 
pander(">> (3) 數據樣貌為:\n\n"); 

kable(head(X,4)) %>%    #make a table
  kable_styling(c("striped", "bordered")) %>% 
  kable_styling(full_width = F) %>% 
  column_spec(1, bold = T)
```

## (KDD2) 
```{r, echo=FALSE, warning=FALSE}
#range(X$Rating) 
rating_cut = table( cut(X$Rating, breaks=c(0,1,2,3,4,5)) );

#@
#https://blog.gtwang.org/r/ggplot2-tutorial-basic-concept-and-qplot/ 
pander(paste0(">> 資料區間[1] Rating 在 0-1 之間",rating_cut[1],"筆\n\n"));  
pander(paste0(">> 資料區間[2] Rating 在 1-2 之間",rating_cut[2],"筆\n\n")); 
pander(paste0(">> 資料區間[3] Rating 在 2-3 之間",rating_cut[3],"筆\n\n")); 
pander(paste0(">> 資料區間[4] Rating 在 3-4 之間",rating_cut[4],"筆\n\n")); 
pander(paste0(">> 資料區間[5] Rating 在 4-5 之間",rating_cut[5],"筆\n\n")); 
pander(paste0(">> Rating 的直方分佈圖")); 

library(ggplot2)
qplot(X$Rating)
```


## (KDD3) 
```{r, echo=FALSE, warning=FALSE}
X.hc = hclust( dist( X[,c("Rating","Reviews","Installs")] ),method="ward.D")
X.group = cutree(X.hc, k=20)
Ncls = 20  #cause k =20
#X[which(X.group==1),c("Rating","Reviews","Installs")]                                   # Rating  Reviews Installs 
X.max = round(apply(X[which(X.group==1),c("Rating","Reviews","Installs")], 2, max),0)   # 5      6477    10000      -max
X.min = round(apply(X[which(X.group==1),c("Rating","Reviews","Installs")], 2, min),0)   # 1      1       1          -min
X.mean = round(apply(X[which(X.group==1),c("Rating","Reviews","Installs")], 2, mean),2) # 4.11   145.01  4646.57    -mean
X.sd = round(apply(X[which(X.group==1),c("Rating","Reviews","Installs")], 2, sd),2)     # 0.73   360.82  4272.84    -sd

#@
pander(paste0(">> (1) 預設 K 值去得知其分群度：k=",Ncls,"\n\n"));
pander(paste0(">> (2) 最大值(Max)：Rating值 ",X.max[1],
              "/ Reviews值",X.max[2],
              "/ Installs值",X.max[3],"\n\n"));

pander(paste0(">> (3) 最小值(Min)：Rating值 ",X.min[1],
              "/ Reviews值",X.min[2],
              "/ Installs值",X.min[3],"\n\n"));

pander(paste0(">> (4) 平均值(Mean)：Rating值 ",X.mean[1],
              "/ Reviews值",X.mean[2],
              "/ Installs值",X.mean[3],"\n\n"));

pander(paste0(">> (4) 標準差(STD)：Rating值 ",X.sd[1],
              "/ Reviews值",X.sd[2],
              "/ Installs值",X.sd[3],"\n\n"));

pander(paste0(">> 在 ward.D 演算法下的分群分析\n\n"));  
kable(table(X.group)) %>%    #make a table
  kable_styling(c("striped", "bordered")) %>% 
  kable_styling(full_width = F) %>% 
  column_spec(1, bold = T)
```


## (KDD4) 
```{r, echo=FALSE, warning=FALSE}
kk = 1  #X.group(kk)
indKK = which(X.group==kk); 
Gmean = NULL
for (kk in 1:Ncls) {
  indKK = which(X.group==kk);
  c(kk,length(indKK), apply(X[indKK,c("Rating","Reviews","Installs")], 2, mean))
  Gmean = rbind(Gmean, c(kk,length(indKK), apply(X[indKK,c("Rating","Reviews","Installs")], 2, mean)))  
}
#round(Gmean[1,],2)
AA = paste0(round(Gmean[1,3:5],2), " * ", colnames(Gmean)[3:5]);  #AA
BB = paste( AA, collapse=" + ");   #BB
# "4.1 * Rating + 145 * Reviews + 4646.6 * Installs"
round(Gmean[1,4],0)

Gmean[1,4]

#@
pander(">> (1)前20大類別總覽分布圖:平均值\n\n");
pander(paste0(">> (2) 可以看出 Rating值在",round(Gmean[1,3],0),
              "/ Reviews值",round(Gmean[1,4],0),
              "/ Installs值",round(Gmean[1,5],0),
              "的總數最多，共",round(Gmean[1,2],0),"筆\n\n"));

kable(round(Gmean,0)[order(Gmean[,2],decreasing=T),])%>%
  kable_styling(c("striped", "bordered")) %>% 
  kable_styling(full_width = F) %>% 
  column_spec(1, bold = T)
```


## (KDD5) 
```{r, echo=FALSE, warning=FALSE}
Gfeature = NULL
for (k in 1:dim(Gmean)[1]) {
  #print(k)
  AA = paste0(round(Gmean[k,3:5],2), " * ", colnames(Gmean)[3:5]);  #AA
  BB = paste( AA, collapse="+")
  #print(BB)
  Gfeature[k] = BB
}; #Gfeature
#write.csv(Gm,"Gm.csv")

#@
pander(">> (1)轉換成 Gfeature 的數據框（顯示前五筆）\n\n"); 
Gm =as.data.frame(Gmean); #head(Gm,2)
colnames(Gm)[1:2] = c("id","count");   #head(Gm,2)
Gm$feature = Gfeature

kable(head(Gm,5))%>%
  kable_styling(c("striped", "bordered")) %>% 
  kable_styling(full_width = F) %>% 
  column_spec(1, bold = T)
```


##--- Rtech04 關聯性分析 ----
```{r, echo=FALSE, warning=FALSE, results="hide"}
library(arules)
library(igraph)

#summary(X)
#table(X$Category)

PD=table(X$Category,X$Year)  
rownames(PD) = NULL;  #PD     # 1-33個品項  #PD[1:10,] 
txPD = lapply( 1:dim(PD)[1], 
               FUN=function(k) colnames(PD)[which(PD[k,]>0)] )
arPD = apriori( txPD[1:6], 
                parameter=list(support=0.06, confidence=0.8), 
                control=list(verbose=FALSE))
a.in = inspect(arPD[3:31,])
alhs = inspect(arPD)[3:31,]$lhs
arhs = inspect(arPD)[3:31,]$rhs

#catch 1-6 year only
#inPD = inspect(arPD[9:20,])
#graph.arPD = graph.edgelist( cbind(inspect(arPD)[1:50,]$lhs, inspect(arPD)[1:50,]$rhs) )
#plot(graph.arPD, edge.arrow.size=0.1, edge.curved=0.3)
```

```{r, echo=FALSE, warning=FALSE}
#@
# apriori演算法大概是這樣運作的，我們必須要設定support以及confidence:
pander(">> (1)我們採用 apriori 演算法\n\n"); 
pander(">> (2)支持度(support)：「規則」在資料內具有普遍性，也就是這些 A 跟 B 同時出現的機率多少\n\n"); 
pander(">> (3)信賴度(confidence)：「規則」要有一定的信心水準，也就是當購買 A 狀態下，也會購買 B 的條件機率\n\n")
#kable(inspect(arPD[3:31,]))%>%
kable(a.in)%>%
  kable_styling(c("striped", "bordered")) %>% 
  kable_styling(full_width = F) %>% 
  column_spec(1, bold = T)
pander(">> lhs=>rhs 代表左邊有，右邊也有的意思（普遍性與信心水準）\n\n"); 
pander(">> 總結： 中心點年份與個年份的關聯性最多 \n\n"); 
plot(graph.edgelist( cbind(alhs, arhs) ), edge.arrow.size=0.1, edge.curved=0.3);
```

##----------以下測試用代碼 --------------

## ggplt
```{r plotexample, fig.width=2, fig.height=2, fig.align='center'}
library(ggplot2)
ggplot(data=data.frame(x=c(1:100),y=sin(0.1*c(1:100)))) +
geom_line(aes(x=x,y=y))
```

## Including Plots

You can also embed plots, for example:
```{r, echo=FALSE, warning=FALSE}
```

```{r pressure, echo=FALSE}
plot(Gmean)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
